FROM quay.balgroupit.com/baloise-base-images/python:3-ubuntu18.04 AS base

RUN apt-get install -y --no-install-recommends git \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/gitopscli

COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt

COPY . .

FROM base AS quality-gate

RUN python3 -m pip install black pylint
RUN black --check -l 120 -t py37 gitopscli
RUN pylint gitopscli

FROM base AS final

RUN python3 -m pip install .

ENTRYPOINT ["gitopscli"]