name: Release

on:
  push:
    branches:
      - master

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docs
        uses: docker/build-push-action@v4
        with:
          context: .
          target: docs-site
          outputs: type=local,dest=.
      - name: Deploy docs to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

  release:
    if: github.repository == 'baloise/gitopscli'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        uses: docker/build-push-action@v4
        with:
          context: .
          target: test
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install semantic-release @semantic-release/exec semantic-release-replace-plugin conventional-changelog-conventionalcommits
      - name: Release
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKER_IMAGE: baloise/gitopscli
          DOCKER_BUILDKIT: '1' # use BuildKit backend (https://docs.docker.com/engine/reference/builder/#buildkit)
          BUILDKIT_PROGRESS: plain
        run: npx semantic-release
